// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.grpc.greet;

public final class Greet {
  private Greet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Greeting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Greeting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GreetEveryoneRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GreetEveryoneRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GreetEveryoneResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GreetEveryoneResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013greet.proto\"1\n\010Greeting\022\022\n\nfirst_name\030" +
      "\001 \001(\t\022\021\n\tlast_name\030\002 \001(\t\"3\n\024GreetEveryon" +
      "eRequest\022\033\n\010greeting\030\001 \001(\0132\t.Greeting\"\'\n" +
      "\025GreetEveryoneResponse\022\016\n\006result\030\001 \001(\t2T" +
      "\n\014GreetService\022D\n\rgreetEveryone\022\025.GreetE" +
      "veryoneRequest\032\026.GreetEveryoneResponse\"\000" +
      "(\0010\001B\022\n\016com.grpc.greetP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Greeting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Greeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Greeting_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_GreetEveryoneRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GreetEveryoneRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GreetEveryoneRequest_descriptor,
        new java.lang.String[] { "Greeting", });
    internal_static_GreetEveryoneResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GreetEveryoneResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GreetEveryoneResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
