// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.grpc.greet;

public interface GreetEveryoneRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GreetEveryoneRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Greeting greeting = 1;</code>
   * @return Whether the greeting field is set.
   */
  boolean hasGreeting();
  /**
   * <code>.Greeting greeting = 1;</code>
   * @return The greeting.
   */
  com.grpc.greet.Greeting getGreeting();
  /**
   * <code>.Greeting greeting = 1;</code>
   */
  com.grpc.greet.GreetingOrBuilder getGreetingOrBuilder();
}
